/*
 * swaggerpetstore_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package SwaggerPetstoreClient

import(
	"swaggerpetstore_lib/configuration_pkg"
	"swaggerpetstore_lib/pet_pkg"
	"swaggerpetstore_lib/store_pkg"
	"swaggerpetstore_lib/user_pkg"
)
/*
 * Client structure as interface implementation
 */
type SWAGGERPETSTORE_IMPL struct {
     pet pet_pkg.PET
     store store_pkg.STORE
     user user_pkg.USER
     config  configuration_pkg.CONFIGURATION
}

/**
     * Access to Configuration
     * @return Returns the Configuration instance
*/
func (me *SWAGGERPETSTORE_IMPL) Configuration() configuration_pkg.CONFIGURATION {
    return me.config
}
/**
     * Access to Pet controller
     * @return Returns the Pet() instance
*/
func (me * SWAGGERPETSTORE_IMPL) Pet() pet_pkg.PET {
    if(me.pet) == nil {
        me.pet = pet_pkg.NewPET(me.config)
    }
    return me.pet
}
/**
     * Access to Store controller
     * @return Returns the Store() instance
*/
func (me * SWAGGERPETSTORE_IMPL) Store() store_pkg.STORE {
    if(me.store) == nil {
        me.store = store_pkg.NewSTORE(me.config)
    }
    return me.store
}
/**
     * Access to User controller
     * @return Returns the User() instance
*/
func (me * SWAGGERPETSTORE_IMPL) User() user_pkg.USER {
    if(me.user) == nil {
        me.user = user_pkg.NewUSER(me.config)
    }
    return me.user
}
