/*
 * swaggerpetstore_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package user_pkg

import "swaggerpetstore_lib/models_pkg"
import "swaggerpetstore_lib/configuration_pkg"

/*
 * Interface for the USER_IMPL
 */
type USER interface {
    CreateUser (*models_pkg.User) (error)

    CreateUsersWithArrayInput ([]*models_pkg.User) (error)

    CreateUsersWithListInput ([]*models_pkg.User) (error)

    GetLoginUser (string, string) (string, error)

    GetLogoutUser () (error)

    GetUserByName (string) (*models_pkg.User, error)

    UpdateUser (string, *models_pkg.User) (error)

    DeleteUser (string) (error)
}

/*
 * Factory for the USER interaface returning USER_IMPL
 */
func NewUSER(config configuration_pkg.CONFIGURATION) *USER_IMPL {
    client := new(USER_IMPL)
    client.config = config
    return client
}