/*
 * swaggerpetstore_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package store_pkg

import "swaggerpetstore_lib/models_pkg"
import "swaggerpetstore_lib/configuration_pkg"

/*
 * Interface for the STORE_IMPL
 */
type STORE interface {
    GetInventory () (map[string]int64, error)

    CreatePlaceOrder (*models_pkg.Order) (*models_pkg.Order, error)

    GetOrderById (int64) (*models_pkg.Order, error)

    DeleteOrder (int64) (error)
}

/*
 * Factory for the STORE interaface returning STORE_IMPL
 */
func NewSTORE(config configuration_pkg.CONFIGURATION) *STORE_IMPL {
    client := new(STORE_IMPL)
    client.config = config
    return client
}